### ISSUE TITLE
Download link currently invalid

### ISSUE THREAD

**Issue by dirtyformal** [RepeaterCreeper/ATC-Buddy#9]
When trying to download a release of ATC-Buddy from this page, a ERR_NAME_NOT_RESOLVED error appears.

**Comment by renorris** [comment]
@dirtyformal Hello, I have updated the 1.2.0 release page which should now include a working link for the Windows binaries. https://github.com/RepeaterCreeper/ATC-Buddy/releases/tag/v1.2.0
